### ISSUE TITLE
adapt issue

### ISSUE THREAD

**Issue by USBzaki** [alidemir45/MachineLearningOnArduinoUno#1]
Hi
First thank you for the project its very interesting 
but
i may had some issues around here 
well i simulate your project & it works just fine but a learning machine must adapt to changes what i did is to change the start point from "Room 0" as you explained to "Room 4" { i switched the pin wires between Room0&Room4  } wile waiting from the robot to adapt to the new shorter way to the "Room 6" it still taking the path of " Room4 >Room1 >Room2 >Room6 " in contrary the bot must adapt to the path " Room4 >Room2 >Room6" 
any explanation & cant it be fixed?
( in the image bellow i only presented the resistors just to make the diagram simpler )
   

thank you
Best regards

**Comment by USBzaki** [comment]
![untitled](https://user-images.githubusercontent.com/33156238/32108885-f30df436-bb2a-11e7-8d4d-78ffd1f0a9f8.png)

**Comment by USBzaki** [comment]
![untitled](https://user-images.githubusercontent.com/33156238/32116619-493f918a-bb43-11e7-8c87-4514d38a85e9.png)

**Comment by alidemir1** [comment]
Actually in order to define new starting point you should change value of the "state" variable in the code. **Keep the wires in their original positions and only change the "state = 0" lines (there are two lines you need to change) in the code with "state = 4"** or to the number of the room that you desire to be the initial state.

**Comment by USBzaki** [comment]
thank you for your time it works perfectly 

Best Regards
